CXX = g++
CXXFLAGS = -Wall
LDLIBS = -lpthread

PROGRAMS = pthread_test1 pthread_test2 thread_tcp_server mutex condition_variable practice1 practice34 practice5

all: $(PROGRAMS)

clean:
	rm -f $(PROGRAMS)