CXX = g++
CXXFLAGS = -Wall
LDLIBS = -lpthread

PROGRAMS = udp_server udp_client udp_server6 udp_client6 broadcast_sender broadcast_receiver \
	practice_12 practice_34 practice_5_client practice_5_server

all: $(PROGRAMS)

clean:
	rm -f $(PROGRAMS)